import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { useFetchUser } from '../lib/user'
import Layout from '../components/Layout'


// TODO: Add CRUD API backend. Here is the link https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-dynamo-db.html
// TODO: Put orders, customers in DB
// TODO: Add Storybook Components
// TODO: Add authentication aith Auth0
// TODO: Add Redux (or other state management)
// TODO: add storybook.
// TODO: Add FORMIK
// TODO: Add testing libraries.

const Home: NextPage = () => {
  const { user, loading } = useFetchUser()

  return (

    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<main>
{/* TODO: Add menu bar */}
  <h1>Here i am</h1>
  {/* TODO: Add Login */}
   <Layout user={user} loading={loading}>
      <h1>Next.js and Auth0 Example</h1>

      {loading && <p>Loading login info...</p>}

      {!loading && !user && (
        <>
          <p>
            To test the login click in <i>Login</i>
          </p>
          <p>
            Once you have logged in you should be able to click in{' '}
            <i>Profile</i> and <i>Logout</i>
          </p>
        </>
      )}

      {user && (
        <>
          <h4>Rendered user info on the client</h4>
          <img src={user.picture} alt="user picture" />
          <p>nickname: {user.nickname}</p>
          <p>name: {user.name}</p>
        </>
      )}
    </Layout>
</main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
